[versions]
minecraft = "1.21.11"
fabric-loader = "0.16.5"
loom = "1.14.3"
meteor = "0.5.8"
fabric-api = "0.108.0+1.21.11"

[libraries]
fabric-api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
meteor-client = { module = "meteordevelopment:meteor-client", version.ref = "meteor" }

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "loom" }
