name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Delete old broken files
        run: rm -rf src/main/java/com/example/
      - name: Build
        run: chmod +x ./gradlew && ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: DoomClient
          path: build/libs/*.jar
